/*
 * This source file was generated by the Gradle 'init' task
 */
package org.wilkinsonk.sbc;

public class SoulardiganBackyard {
    /**
     * The version of Soulardigan Backyard.
     */
    public static final String BUILD_VERSION = "1.0.0";
    /**
     * The name used for prefixing categories and
     * subcategories of assets used throughout a plugin.
     */
    public static final String NAME = "sbc";
    /**
     * The fully qualified name of the plugin.
     */
    public static final String NAME_LONG = "soulardigan-backyard";
    /**
     * The human readable plugin name.
     */
    public static final String TITLE = "Soulardigan Backyard";
}
