/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    `java-library`
    id("maven-publish")
}

repositories {
    maven {
        name = "papermc"
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:${property("papermc_api_version")}")
    compileOnly("com.velocitypowered:velocity-api:${property("velocity_api_version")}")
    annotationProcessor("com.velocitypowered:velocity-api:${property("velocity_api_version")}")
    implementation(project(":sbc:common"))
}

base {
    archivesName.set(property("archive_base_name").toString())
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.jar {
    from(project(":sbc:common").sourceSets.main.get().output)
}
